# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/hpoupard/Desktop/modulation_audio_2/modulation_audio_2.cache/wt [current_project]
set_property parent.project_path C:/Users/hpoupard/Desktop/modulation_audio_2/modulation_audio_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/hpoupard/Desktop/modulation_audio_2/modulation_audio_2.srcs/sources_1/new/uart_recv.vhd
  C:/Users/hpoupard/Desktop/modulation_audio_2/modulation_audio_2.srcs/sources_1/new/stop_counter.vhd
  C:/Users/hpoupard/Desktop/modulation_audio_2/modulation_audio_2.srcs/sources_1/new/merger_8b_to_16b.vhd
  C:/Users/hpoupard/Desktop/modulation_audio_2/modulation_audio_2.srcs/sources_1/new/cmp_addr.vhd
  C:/Users/hpoupard/Desktop/modulation_audio_2/modulation_audio_2.srcs/sources_1/new/ROM_Sinus.vhd
  C:/Users/hpoupard/Desktop/modulation_audio_2/modulation_audio_2.srcs/sources_1/new/pwm.vhd
  C:/Users/hpoupard/Desktop/modulation_audio_2/modulation_audio_2.srcs/sources_1/new/horloge_44100Hz.vhd
  C:/Users/hpoupard/Desktop/modulation_audio_2/modulation_audio_2.srcs/sources_1/new/full_uart_recv.vhd
  C:/Users/hpoupard/Desktop/modulation_audio_2/modulation_audio_2.srcs/sources_1/new/synthese_totale.vhd
}
read_xdc C:/Users/hpoupard/Desktop/modulation_audio_2/modulation_audio_2.srcs/constrs_1/new/routage.xdc
set_property used_in_implementation false [get_files C:/Users/hpoupard/Desktop/modulation_audio_2/modulation_audio_2.srcs/constrs_1/new/routage.xdc]

synth_design -top synthese_totale -part xc7a100tcsg324-1
write_checkpoint -noxdef synthese_totale.dcp
catch { report_utilization -file synthese_totale_utilization_synth.rpt -pb synthese_totale_utilization_synth.pb }
