# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/hpoupard/Desktop/space_invaders/space_invaders.cache/wt [current_project]
set_property parent.project_path C:/Users/hpoupard/Desktop/space_invaders/space_invaders.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/hpoupard/Desktop/space_invaders/space_invaders.srcs/sources_1/new/vga_640_480.vhd
  C:/Users/hpoupard/Desktop/space_invaders/space_invaders.srcs/sources_1/new/charg_memoire.vhd
  C:/Users/hpoupard/Desktop/space_invaders/space_invaders.srcs/sources_1/new/top_module.vhd
}
read_xdc C:/Users/hpoupard/Desktop/space_invaders/space_invaders.srcs/constrs_1/new/contrainte.xdc
set_property used_in_implementation false [get_files C:/Users/hpoupard/Desktop/space_invaders/space_invaders.srcs/constrs_1/new/contrainte.xdc]

synth_design -top top_module -part xc7a100tcsg324-1
write_checkpoint -noxdef top_module.dcp
catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
